[package]
name = "kaori-rtos"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kaori-hsm = "0.1.1"
cortex-m = {version="0.7.7", features=["critical-section-single-core"]}
